# eval `ssh-agent -s`
# ssh-add

- name: Clone .dotfiles repository
  ansible.builtin.git:
    repo: git@github.com:dpletiko/.dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: true
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tags:
    - skip_ansible_lint


- name: Symlink tmux
  ansible.builtin.file:
    src: ~/.dotfiles/tmux/.tmux.conf
    dest: ~/.tmux.conf
    state: link


- name: Symlink nvim
  ansible.builtin.file:
    src: ~/.dotfiles/nvim
    dest: ~/.config/nvim
    state: link


- name: Symlink i3
  ansible.builtin.file:
    src: ~/.dotfiles/i3
    dest: ~/.config/i3
    state: link


- name: Symlink i3blocks
  ansible.builtin.file:
    src: ~/.dotfiles/i3blocks/calendar
    dest: ~/.config/i3blocks/calendar/calendar
    state: link
    force: true


