- name: System update
  become: true
  ansible.builtin.apt:
    update_cache: true


- name: Check if cargo is installed
  ansible.builtin.shell: command -v cargo
  register: cargo_exists
  ignore_errors: true


- name: Install cargo
  when: cargo_exists is failed
  # become: true
  ansible.builtin.shell: >
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/cargo"


- name: Source cargo env
  # when: cargo_exists is true
  ansible.builtin.shell: ". {{ lookup('env', 'HOME') }}/.cargo/env"


- name: Rustup source stable
  ansible.builtin.shell: "source {{ lookup('env', 'HOME') }}/.bashrc && rustup default stable"
  args:
    executable: /bin/bash


- name: Install cargo packages
  # when: cargo_exists is true
  community.general.cargo:
    name: "{{ item }}"
    state: present
    # executable: "{{ lookup('env', 'HOME') }}/.cargo/bin/cargo"
  with_items: "{{ cargo_packages }}"
