- name: Install PHP
  ansible.builtin.package:
    name: 'php{{ item }}'
    state: present
  loop: '{{ php_versions }}'


- name: Install PHP Extensions
  ansible.builtin.package:
    name: 'php{{ item.0 }}-{{ item.1 }}'
    state: present
  loop: "{{ php_versions|product(php_extensions)|list }}"


# or include_tasks
- import_tasks: setup_databases.yml
