- name: Print env HOME
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'HOME') }}"


- name: System update
  become: true
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: true


- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - make
    - cmake
    - git
    - tmux
    - nginx
    - python3.11-venv


- name: Install TPM (TMux Plugin Manager)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
  tags:
    - skip_ansible_lint


# or include_tasks
- name: Setup NeoVim
  ansible.builtin.import_tasks: setup_nvim.yml


- name: Setup NodeJS
  ansible.builtin.import_tasks: setup_node.yml


- name: Setup PHP
  ansible.builtin.import_tasks: setup_php.yml
