- name: Print env HOME
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'HOME') }}"


- name: System update
  become: true
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: true


- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    # - lsb-release
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - gnupg
    - curl
    - make
    - cmake
    - git
    - libpq-dev
    - libsqlite3-dev
    - default-libmysqlclient-dev


- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: false
  with_items:
    - virtualenv
    - python3-pip
    - python3.11-venv
    - python3-setuptools


- name: Setup Tmux
  ansible.builtin.import_tasks: setup_tmux.yml
  tags: "common:tmux"


- name: Setup NeoVim
  ansible.builtin.import_tasks: setup_nvim.yml
  tags: "common:nvim"


- name: Setup i3
  ansible.builtin.import_tasks: setup_i3.yml
  tags: "common:i3"


- name: Setup zsh
  ansible.builtin.import_tasks: setup_zsh.yml
  tags: "common:zsh"

