# ln -s .tmux.conf
# prefix + I >> install plugins

- name: Install packages
  ansible.builtin.package:
    name: tmux
    state: present
  become: true


- name: Install TPM (TMux Plugin Manager)
  become: true
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
