- name: Add Docker repository keyrings
  become: true
  ansible.builtin.shell: >
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg


- name: Set appropriate permissions
  ansible.builtin.file:
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0444'


- name: Setting architecture fact
  ansible.builtin.set_fact:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"


- name: Add Docker repository to sources
  become: true
  ansible.builtin.apt_repository:
    filename: docker
    repo: 'deb [arch="{{ arch }}" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian/ {{ ansible_distribution_release }} stable'


- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    # - docker-compose-plugin
    # - python3-docker


- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
    virtualenv: "{{ lookup('env', 'HOME') }}/.local"
