- name: Install NVM (Node Version Manager)
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"


# - name: Install NodeJS
#   ansible.builtin.shell: "nvm install {{ node }}"
#   loop: '{{ node_versions }}'
#   loop_control:
#     loop_var: node
#
