php_versions:
  - 5.6
  - 7.2
  - 7.3
  - 7.4
  - 8.2

php_extensions:
  - cli
  - curl
  - common
  - bcmath
  - gd
  - dom
  - xml
  - mbstring
  - intl
  - zip
  - pgsql
  - mysql


node_versions:
  - node
  - lts/gallium
  - lts/hydrogen
  - lts/*


node_global_packages:
  - yarn


cargo_packages:
  - cargo-watch
  - diesel_cli


flutter_versions:
  - 1.22.6
  - 3.16.0
  - stable
