- name: "Ensures dir exists | /docker/{{ database.key }}"
  become: true
  ansible.builtin.file:
    path: "/docker/{{ database.key }}"
    state: directory
    mode: '0755'


- name: "Ensure docker-compose.yml exists | /docker/{{ database.key }}"
  become: true
  loop: "{{ database.value }}"
  ansible.builtin.template:
    src: docker-compose.db.yml.j2
    dest: "/docker/{{ database.key }}/docker-compose.yml"
    mode: '0666'


- name: "Start docker services | /docker/{{ database.key }}"
  ansible.builtin.command:
    chdir: "/docker/{{ database.key }}"
    cmd: docker compose up -d
  register: output


# - name: "Deploy {{ database.key }}"
#   become: true
#   community.docker.docker_compose:
#     project_src: "/docker/{{ database.key }}/"
#     files:
#       - docker-compose.yml
#   register: output


- name: Show results
  ansible.builtin.debug:
    var: output


# - name: "Verify that {{ database.key }} services are running"
#   ansible.builtin.assert:
#     that:
#       - "not output.services.db.flask_db_1.state.running"
